[package]
name = "rudp-socket-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rudp_protocol_kit = { path = "../rudp-protocol-kit" }
storage_kit = { path = "../storage-kit" }
