FROM rust:latest as builder

WORKDIR /app
COPY . .

# Build the server
RUN cargo build --release --package server

FROM debian:buster-slim
COPY --from=builder /app/target/release/server /usr/local/bin/server

ENTRYPOINT ["/usr/local/bin/server"]
